name: tugas2_gpa38
description: "Project Implementasi Desain UI/UX Kelas GPA38A - 2025"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  firebase_core:
  firebase_auth:
  firebase_auth_web:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/


